### PR TITLE
Follow Ethereum revert message rule

### PR DESCRIPTION
**Pull request by AsceticBear**
The application side gets ethabi error message like the below:
image

Then decode it to readable content:

```
$ ethabi decode params -t string 000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000194e6f7420737570706f72746564206572726f7220696e64657800000000000000
string Not supported error index
```

QA about this: https://ethereum.stackexchange.com/questions/76653/how-to-decode-error-response-from-contact

### CODE REVIEW

**Comment by AsceticBear** [comment]
@hujw77 @wuminzhe Please take a review

**Review by hujw77 — COMMENTED** [review]
I think the error message is too long, The message length less than 32 would be better.

**Comment by AsceticBear** [comment]
> I think the error message is too long, The message length less than 32 would be better.

Make sense. I have done some updates, please check it again.

**Review by wuminzhe — APPROVED** [review]

**Review by hujw77 — APPROVED** [review]
LGTM

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
