### PR TITLE
feat: migrate crab backing to use pallet!

### PR DESCRIPTION
**Pull request by songtianyi**
Part of #561.

Converts the crab backing pallet to the new pallet attribute macro introduced in [#6877](https://github.com/paritytech/substrate/pull/6877).

[Upgrade guidelines used](https://substrate.dev/rustdocs/v3.0.0/frame_support/attr.pallet.html#upgrade-guidelines).

⚠️ Breaking Change ⚠️
From [checking upgrade guidelines](https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines)

> storages now use PalletInfo for module_prefix instead of the one given to decl_storage: use of this pallet in construct_runtime! needs careful updating of the name in order to not break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

Common notes
- their Trait is renamed Config
- all storages are now generic over T
- module prefix used by storages is now the PalletInfo::name given by construct_runtime.
- no longer RawEvent.

The metadata for CrabBacking before migration
```json
   {
          name: CrabBacking,
          storage: {
            prefix: DarwiniaCrabBacking,
            items: []
          },
          calls: null,
          events: null,
          constants: [
            {
              name: ModuleId,
              type: ModuleId,
              value: da/crabk,
              documentation: []
            }
          ],
          errors: [],
          index: 34
        },
```
The metadata for CrabBacking after migration
```json
  {
          name: DarwiniaCrabBacking,
          storage: {
            prefix: DarwiniaCrabBacking,
            items: []
          },
          calls: null,
          events: null,
          constants: [
            {
              name: ModuleId,
              type: ModuleId,
              value: da/crabk,
              documentation: []
            }
          ],
          errors: [],
          index: 34
        },
       
```

### CODE REVIEW

**Comment by HackFisher** [comment]
To keep the crab backing pallet storage prefix unchanged,

[Suggest] ensure that the name of the pallet given to construct_runtime! is the same as the name the pallet was giving to decl_storage, update it to `DarwiniaCrabBacking `.

or do a storage migration from the old prefix used to the new prefix used.

https://github.com/darwinia-network/darwinia-common/blob/48f7efd15a23d41da83615ae6790f669de4cb7c2/bin/node/runtime/pangolin/src/lib.rs#L485

**Comment by songtianyi** [comment]
https://github.com/paritytech/substrate/issues/8391

it seems no solution to specify the storge prefix yet.
I'm trying to do this in contruct_runtime!

**Comment by songtianyi** [comment]
> [paritytech/substrate#8391](https://github.com/paritytech/substrate/issues/8391)
> 
> it seems no solution to specify the storge prefix yet.
> I'm trying to do this in contruct_runtime!

rename CrabBacking to DarwiniaCrabBacking, so the module name changed

**Comment by HackFisher** [comment]
@songtianyi Compile failed and suggest to submit pull requests for each pallet migration.

**Comment by AurevoirXavier** [comment]
Could you follow #568's style?

**Review by HackFisher — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
No storage in this pallet. Migration is not needed.

**Review by AurevoirXavier — APPROVED** [review]

**Pull request merged**
