### PR TITLE
v0.11.1 Preview

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by HackFisher** [comment]
We might need to include London Hardfork changes in v0.11.1 if substrate dep ([darwinia-v0.11.2](https://github.com/darwinia-network/substrate/tree/darwinia-v0.11.2)) will require mandatory upgrade for nodes.

**Comment by AurevoirXavier** [comment]
> We might need to include London Hardfork changes in v0.11.1 if substrate dep ([darwinia-v0.11.2](https://github.com/darwinia-network/substrate/tree/darwinia-v0.11.2)) will require mandatory upgrade for nodes.

I'm testing runtime upgrade base darwinia-v0.11.1-with-old-mmr to darwinia-v0.11.2

**Comment by AurevoirXavier** [comment]
```
λ ./v0.11.1 --unsafe-ws-external --rpc-cors all --dev --tmp
2021-07-27 16:52:50 Darwinia Runtime Module Library    
2021-07-27 16:52:50 ✌️  version 2.4.0-6baed1e2-x86_64-linux-gnu    
2021-07-27 16:52:50 ❤️  by Darwinia Network <hello@darwinia.network>, 2018-2021    
2021-07-27 16:52:50 📋 Chain specification: Pangolin    
2021-07-27 16:52:50 🏷 Node name: safe-year-0897    
2021-07-27 16:52:50 👤 Role: AUTHORITY    
2021-07-27 16:52:50 💾 Database: RocksDb at /tmp/substratekvekLd/chains/pangolin/db    
2021-07-27 16:52:50 ⛓  Native runtime: Pangolin-2401 (Pangolin-1.tx1.au1)    
2021-07-27 16:52:51 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2021-07-27 16:52:51 [#0] 🗳  Finalized election round with compute ElectionCompute::OnChain.    
2021-07-27 16:52:51 [0] 💸 new validator set of size 1 has been processed for era 1    
2021-07-27 16:52:51 [darwinia-claims] Genesis Claims List is Set to EMPTY    
2021-07-27 16:52:51 🔨 Initializing Genesis block/state (state: 0xa086…1087, header-hash: 0x8970…8d3f)    
2021-07-27 16:52:51 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2021-07-27 16:52:51 ⏱  Loaded block-time = 6s from genesis on first-launch    
2021-07-27 16:52:51 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2021-07-27 16:52:51 Using default protocol ID "sup" because none is configured in the chain specs    
2021-07-27 16:52:51 Using default protocol ID "sup" because none is configured in the chain specs    
2021-07-27 16:52:51 🏷 Local node identity is: 12D3KooWRPLTCvv6UsXVTS5j8b8vt62TxxKfdp21c7BAdBmz8KDr    
2021-07-27 16:52:51 📦 Highest known block at #0    
2021-07-27 16:52:51 〽️ Prometheus server started at 127.0.0.1:9615    
2021-07-27 16:52:51 Listening for new connections on 0.0.0.0:9944.    
2021-07-27 16:52:51 👶 Starting BABE Authorship worker    
2021-07-27 16:52:54 🙌 Starting consensus session on top of parent 0x89709db7794d3a95925720e3c250a3d65767ac039a6a6d435b4fdb6129d18d3f    
2021-07-27 16:52:54 🎁 Prepared block for proposing at 1 [hash: 0xc9bc71d55aac7b964645921b3d043bfb00c4dad5f4825d48b2b70cabe0731684; parent_hash: 0x8970…8d3f; extrinsics (2): [0x6934…8b21, 0x42a6…4e6e]]    
2021-07-27 16:52:54 🔖 Pre-sealed block for proposal at 1. Hash now 0x7716cae5018e3bf226475a5cead56f9a28845089ff7892fba763e8189ee950d2, previously 0xc9bc71d55aac7b964645921b3d043bfb00c4dad5f4825d48b2b70cabe0731684.    
2021-07-27 16:52:54 👶 New epoch 0 launching at block 0x7716…50d2 (block slot 271229329 >= start slot 271229329).    
2021-07-27 16:52:54 👶 Next epoch starts at slot 271229429    
2021-07-27 16:52:54 ✨ Imported #1 (0x7716…50d2)    
2021-07-27 16:52:56 💤 Idle (0 peers), best: #1 (0x7716…50d2), finalized #0 (0x8970…8d3f), ⬇ 0 ⬆ 0    
2021-07-27 16:53:00 🙌 Starting consensus session on top of parent 0x7716cae5018e3bf226475a5cead56f9a28845089ff7892fba763e8189ee950d2    
2021-07-27 16:53:00 🎁 Prepared block for proposing at 2 [hash: 0xea2d20f3e6e962cb2e5a1632c6601881ea25270658d661496fd671dcbdb28804; parent_hash: 0x7716…50d2; extrinsics (2): [0x8b39…c590, 0x42a6…4e6e]]    
2021-07-27 16:53:00 🔖 Pre-sealed block for proposal at 2. Hash now 0xd39d319ff5ca1105fce547c3a3813642bd1158666757336ea39f8f3d30aaef3a, previously 0xea2d20f3e6e962cb2e5a1632c6601881ea25270658d661496fd671dcbdb28804.    
2021-07-27 16:53:00 ✨ Imported #2 (0xd39d…ef3a)    
2021-07-27 16:53:01 💤 Idle (0 peers), best: #2 (0xd39d…ef3a), finalized #0 (0x8970…8d3f), ⬇ 0 ⬆ 0    
2021-07-27 16:53:06 🙌 Starting consensus session on top of parent 0xd39d319ff5ca1105fce547c3a3813642bd1158666757336ea39f8f3d30aaef3a    
2021-07-27 16:53:06 🎁 Prepared block for proposing at 3 [hash: 0x1368d253822462845638da77612429ff0d4ed6f47fdb1a678794d2431c2e0b0e; parent_hash: 0xd39d…ef3a; extrinsics (2): [0x4f67…b86b, 0x42a6…4e6e]]    
2021-07-27 16:53:06 🔖 Pre-sealed block for proposal at 3. Hash now 0xa937705adae73691c49c33b06a6d0b3544a2fc6e007a84e1d7e6ce684c7212d1, previously 0x1368d253822462845638da77612429ff0d4ed6f47fdb1a678794d2431c2e0b0e.    
2021-07-27 16:53:06 ✨ Imported #3 (0xa937…12d1)    
2021-07-27 16:53:06 💤 Idle (0 peers), best: #3 (0xa937…12d1), finalized #0 (0x8970…8d3f), ⬇ 0 ⬆ 0    
2021-07-27 16:53:08 Accepted a new tcp connection from 49.65.112.251:52168.    
2021-07-27 16:53:11 💤 Idle (0 peers), best: #3 (0xa937…12d1), finalized #0 (0x8970…8d3f), ⬇ 0 ⬆ 0    
2021-07-27 16:53:11 Accepted a new tcp connection from 49.65.112.251:52170.    
2021-07-27 16:53:12 🙌 Starting consensus session on top of parent 0xa937705adae73691c49c33b06a6d0b3544a2fc6e007a84e1d7e6ce684c7212d1    
2021-07-27 16:53:12 🎁 Prepared block for proposing at 4 [hash: 0xb1d2ccbdc443f098248f6d78171a883172be42513e3646780f646d923ff738d1; parent_hash: 0xa937…12d1; extrinsics (2): [0x0284…fd93, 0x42a6…4e6e]]    
2021-07-27 16:53:12 🔖 Pre-sealed block for proposal at 4. Hash now 0x830e2fd2df1b620d9546d492d8fa568259c97321995ba50ee051581a82be164f, previously 0xb1d2ccbdc443f098248f6d78171a883172be42513e3646780f646d923ff738d1.    
2021-07-27 16:53:12 ✨ Imported #4 (0x830e…164f)    
2021-07-27 16:53:16 💤 Idle (0 peers), best: #4 (0x830e…164f), finalized #2 (0xd39d…ef3a), ⬇ 0 ⬆ 0    
2021-07-27 16:53:18 🙌 Starting consensus session on top of parent 0x830e2fd2df1b620d9546d492d8fa568259c97321995ba50ee051581a82be164f    
2021-07-27 16:53:18 🎁 Prepared block for proposing at 5 [hash: 0xf9abbaf02bcf76b6f84228cd20f04bfeea000fdd699620da0b6edd6f9e90ae01; parent_hash: 0x830e…164f; extrinsics (2): [0x1678…2ccb, 0x42a6…4e6e]]    
2021-07-27 16:53:18 🔖 Pre-sealed block for proposal at 5. Hash now 0x3341eafe6696dfe7dcc7fd26508fea79e6fea67c233c2b41f846ccf3ee6e6c62, previously 0xf9abbaf02bcf76b6f84228cd20f04bfeea000fdd699620da0b6edd6f9e90ae01.    
2021-07-27 16:53:18 ✨ Imported #5 (0x3341…6c62)    
2021-07-27 16:53:21 💤 Idle (0 peers), best: #5 (0x3341…6c62), finalized #2 (0xd39d…ef3a), ⬇ 0 ⬆ 0    
2021-07-27 16:53:24 🙌 Starting consensus session on top of parent 0x3341eafe6696dfe7dcc7fd26508fea79e6fea67c233c2b41f846ccf3ee6e6c62    
2021-07-27 16:53:24 🎁 Prepared block for proposing at 6 [hash: 0x525a123aa875c8664f7aead43cca6e3260e69d81673457c0ffd348e522a3742b; parent_hash: 0x3341…6c62; extrinsics (2): [0x3cad…53e1, 0x42a6…4e6e]]    
2021-07-27 16:53:24 🔖 Pre-sealed block for proposal at 6. Hash now 0x49ab77d5ec8ca67fbed94c85cb8961a89c3155afe37d3edcc5a8d90f89059115, previously 0x525a123aa875c8664f7aead43cca6e3260e69d81673457c0ffd348e522a3742b.    
2021-07-27 16:53:24 ✨ Imported #6 (0x49ab…9115)    
2021-07-27 16:53:26 💤 Idle (0 peers), best: #6 (0x49ab…9115), finalized #3 (0xa937…12d1), ⬇ 0 ⬆ 0    
2021-07-27 16:53:30 🙌 Starting consensus session on top of parent 0x49ab77d5ec8ca67fbed94c85cb8961a89c3155afe37d3edcc5a8d90f89059115    
2021-07-27 16:53:30 🎁 Prepared block for proposing at 7 [hash: 0x8d9327419b427d47e61644778c4e34397a712eb18228284869145ab34a787115; parent_hash: 0x49ab…9115; extrinsics (2): [0xa529…a95f, 0x42a6…4e6e]]    
2021-07-27 16:53:30 🔖 Pre-sealed block for proposal at 7. Hash now 0xacf5e56e8b9ea6ce1838c18280a1fef1ffd2d7184de5bf130c576d96e8bee1ca, previously 0x8d9327419b427d47e61644778c4e34397a712eb18228284869145ab34a787115.    
2021-07-27 16:53:30 ✨ Imported #7 (0xacf5…e1ca)    
2021-07-27 16:53:31 💤 Idle (0 peers), best: #7 (0xacf5…e1ca), finalized #4 (0x830e…164f), ⬇ 0 ⬆ 0    
2021-07-27 16:53:36 🙌 Starting consensus session on top of parent 0xacf5e56e8b9ea6ce1838c18280a1fef1ffd2d7184de5bf130c576d96e8bee1ca    
2021-07-27 16:53:36 🎁 Prepared block for proposing at 8 [hash: 0x99175ecdd90b55af730d11c04eb49ff81a7722d9c069a5391786a9cfec9f7df3; parent_hash: 0xacf5…e1ca; extrinsics (2): [0x13a2…5467, 0x42a6…4e6e]]    
2021-07-27 16:53:36 🔖 Pre-sealed block for proposal at 8. Hash now 0x7d9b10642b3f516cc00b2b90ce0650677ac86c4e3b1a02a6baa775a6af24fcce, previously 0x99175ecdd90b55af730d11c04eb49ff81a7722d9c069a5391786a9cfec9f7df3.    
2021-07-27 16:53:36 ✨ Imported #8 (0x7d9b…fcce)    
2021-07-27 16:53:36 💤 Idle (0 peers), best: #8 (0x7d9b…fcce), finalized #5 (0x3341…6c62), ⬇ 0 ⬆ 0    
2021-07-27 16:53:41 💤 Idle (0 peers), best: #8 (0x7d9b…fcce), finalized #6 (0x49ab…9115), ⬇ 0 ⬆ 0    
2021-07-27 16:53:42 🙌 Starting consensus session on top of parent 0x7d9b10642b3f516cc00b2b90ce0650677ac86c4e3b1a02a6baa775a6af24fcce    
2021-07-27 16:53:42 🎁 Prepared block for proposing at 9 [hash: 0x2e81d65524c1f710e81ec12e26feca31cf504b14f5aee8dbf056c2b735546c42; parent_hash: 0x7d9b…fcce; extrinsics (2): [0x3aa3…9b1f, 0x42a6…4e6e]]    
2021-07-27 16:53:42 🔖 Pre-sealed block for proposal at 9. Hash now 0x0beff74b19eee54a27b7c0ca4c5bb4d86e73131bc0010696104c28d30c47461e, previously 0x2e81d65524c1f710e81ec12e26feca31cf504b14f5aee8dbf056c2b735546c42.    
2021-07-27 16:53:42 ✨ Imported #9 (0x0bef…461e)    
2021-07-27 16:53:46 💤 Idle (0 peers), best: #9 (0x0bef…461e), finalized #6 (0x49ab…9115), ⬇ 0 ⬆ 0    
2021-07-27 16:53:48 🙌 Starting consensus session on top of parent 0x0beff74b19eee54a27b7c0ca4c5bb4d86e73131bc0010696104c28d30c47461e    
2021-07-27 16:53:48 🎁 Prepared block for proposing at 10 [hash: 0xf33cff0de24041de247439cd44dc2a9ebf8a4c1446f84389339cb959880f87bf; parent_hash: 0x0bef…461e; extrinsics (2): [0x68eb…0405, 0x42a6…4e6e]]    
2021-07-27 16:53:48 🔖 Pre-sealed block for proposal at 10. Hash now 0x0adfa6436fd8a066ccd8251db5846a6ebdfcd69f337fc0f82550300a526f1ec8, previously 0xf33cff0de24041de247439cd44dc2a9ebf8a4c1446f84389339cb959880f87bf.    
2021-07-27 16:53:48 ✨ Imported #10 (0x0adf…1ec8)    
2021-07-27 16:53:51 💤 Idle (0 peers), best: #10 (0x0adf…1ec8), finalized #7 (0xacf5…e1ca), ⬇ 0 ⬆ 0    
2021-07-27 16:53:54 🙌 Starting consensus session on top of parent 0x0adfa6436fd8a066ccd8251db5846a6ebdfcd69f337fc0f82550300a526f1ec8    
2021-07-27 16:53:54 🎁 Prepared block for proposing at 11 [hash: 0x852eff3ff467ee2a0f5324dbd4ac041946fccf8d79a3b6a661beaf3438aeef03; parent_hash: 0x0adf…1ec8; extrinsics (2): [0xa716…1866, 0x42a6…4e6e]]    
2021-07-27 16:53:54 🔖 Pre-sealed block for proposal at 11. Hash now 0xe0d3f2da3d473d4ad907c2f7a6ff74eb844c2ea1ef8f85d7e595fe7d234d00e1, previously 0x852eff3ff467ee2a0f5324dbd4ac041946fccf8d79a3b6a661beaf3438aeef03.    
2021-07-27 16:53:54 ✨ Imported #11 (0xe0d3…00e1)    
2021-07-27 16:53:56 💤 Idle (0 peers), best: #11 (0xe0d3…00e1), finalized #8 (0x7d9b…fcce), ⬇ 0 ⬆ 0    
2021-07-27 16:54:00 🙌 Starting consensus session on top of parent 0xe0d3f2da3d473d4ad907c2f7a6ff74eb844c2ea1ef8f85d7e595fe7d234d00e1    
2021-07-27 16:54:00 🎁 Prepared block for proposing at 12 [hash: 0x62ff222a1d2176213951ad3e065e739d01942bcad6e10283d05e01f8c687ecf3; parent_hash: 0xe0d3…00e1; extrinsics (3): [0x9188…0a9d, 0x42a6…4e6e, 0x5a7d…d027]]    
2021-07-27 16:54:00 🔖 Pre-sealed block for proposal at 12. Hash now 0x0f7421f73f7219d5bc7e2a0f32a2613d8351397588a0a0694be5c3691a49dfc0, previously 0x62ff222a1d2176213951ad3e065e739d01942bcad6e10283d05e01f8c687ecf3.    
2021-07-27 16:54:00 ✨ Imported #12 (0x0f74…dfc0)    
2021-07-27 16:54:01 💤 Idle (0 peers), best: #12 (0x0f74…dfc0), finalized #9 (0x0bef…461e), ⬇ 0 ⬆ 0    
2021-07-27 16:54:06 🙌 Starting consensus session on top of parent 0x0f7421f73f7219d5bc7e2a0f32a2613d8351397588a0a0694be5c3691a49dfc0    
2021-07-27 16:54:06 🎁 Prepared block for proposing at 13 [hash: 0xdc9caf744d8ca8db91ca19b06aa20f5ccc730b55de859f41d90866fc2cdd09de; parent_hash: 0x0f74…dfc0; extrinsics (2): [0x33cd…8d1f, 0x42a6…4e6e]]    
2021-07-27 16:54:06 🔖 Pre-sealed block for proposal at 13. Hash now 0x5b5c674c3118dae932ccdf60d181a0e8727159171a0455d9454601b80c47334d, previously 0xdc9caf744d8ca8db91ca19b06aa20f5ccc730b55de859f41d90866fc2cdd09de.    
2021-07-27 16:54:06 ✨ Imported #13 (0x5b5c…334d)    
2021-07-27 16:54:06 💤 Idle (0 peers), best: #13 (0x5b5c…334d), finalized #10 (0x0adf…1ec8), ⬇ 0 ⬆ 0    
2021-07-27 16:54:11 💤 Idle (0 peers), best: #13 (0x5b5c…334d), finalized #10 (0x0adf…1ec8), ⬇ 0 ⬆ 0    
2021-07-27 16:54:12 🙌 Starting consensus session on top of parent 0x5b5c674c3118dae932ccdf60d181a0e8727159171a0455d9454601b80c47334d    
2021-07-27 16:54:12 🎁 Prepared block for proposing at 14 [hash: 0x896156252b0acce727a12e712a481171b33f71b2310b7961c1dbf4908fd45cce; parent_hash: 0x5b5c…334d; extrinsics (2): [0xae1a…3bdf, 0x42a6…4e6e]]    
2021-07-27 16:54:12 🔖 Pre-sealed block for proposal at 14. Hash now 0xd8b1844f635bfa1709be9c4977355f163873b0db23dcc93595caf02292b3e803, previously 0x896156252b0acce727a12e712a481171b33f71b2310b7961c1dbf4908fd45cce.    
2021-07-27 16:54:12 ✨ Imported #14 (0xd8b1…e803)    
2021-07-27 16:54:16 💤 Idle (0 peers), best: #14 (0xd8b1…e803), finalized #12 (0x0f74…dfc0), ⬇ 0 ⬆ 0    
2021-07-27 16:54:18 🙌 Starting consensus session on top of parent 0xd8b1844f635bfa1709be9c4977355f163873b0db23dcc93595caf02292b3e803    
2021-07-27 16:54:18 ⚠️  Dropping non-mandatory inherent from overweight block.    
2021-07-27 16:54:18 🎁 Prepared block for proposing at 15 [hash: 0x6162d51480a90d645593a3765a11d265f6e1bd91ec2cf4bac9d4873bbdca49aa; parent_hash: 0xd8b1…e803; extrinsics (1): [0xaf0c…433b]]    
2021-07-27 16:54:18 🔖 Pre-sealed block for proposal at 15. Hash now 0x9d26ba7d033b3435dd1e40f5176a535c8a621f48bf085dc4e23cf44b42a7d212, previously 0x6162d51480a90d645593a3765a11d265f6e1bd91ec2cf4bac9d4873bbdca49aa.    
2021-07-27 16:54:18 ✨ Imported #15 (0x9d26…d212)    
2021-07-27 16:54:18 ⚠️ System declares internal migrations (which *might* execute), setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for BSC, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for BridgeMillauGrandpa, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for BridgeMillauDispatch, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ⚠️ BridgeMillauMessages declares internal migrations (which *might* execute), setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for DynamicFee, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Ethereum, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for EVM, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for TronBacking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for EthereumRelayAuthorities, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for EthereumRelayerGame, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for EthereumIssuing, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for EthereumBacking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for EthereumRelay, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for CrabBacking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for CrabIssuing, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Multisig, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Proxy, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Scheduler, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Recovery, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Society, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Identity, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Utility, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Vesting, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Claims, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Sudo, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Treasury, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for TechnicalMembership, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for PhragmenElection, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for TechnicalCommittee, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Council, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Democracy, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for HeaderMMR, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for AuthorityDiscovery, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for ImOnline, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Grandpa, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Session, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Historical, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ⚠️ Offences declares internal migrations (which *might* execute), setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 have 0 deferred offences, applying.    
2021-07-27 16:54:18 ✅ no migration for Staking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for ElectionProviderMultiPhase, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Authorship, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for TransactionPayment, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Kton, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Balances, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Timestamp, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for Babe, setting storage version to <wasm:stripped>    
2021-07-27 16:54:18 ✅ no migration for RandomnessCollectiveFlip, setting storage version to <wasm:stripped>    
2021-07-27 16:54:21 💤 Idle (0 peers), best: #15 (0x9d26…d212), finalized #12 (0x0f74…dfc0), ⬇ 0 ⬆ 0    
2021-07-27 16:54:24 🙌 Starting consensus session on top of parent 0x9d26ba7d033b3435dd1e40f5176a535c8a621f48bf085dc4e23cf44b42a7d212    
2021-07-27 16:54:24 ⚠️ System declares internal migrations (which *might* execute), setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for BSC, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for BridgeMillauGrandpa, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for BridgeMillauDispatch, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ⚠️ BridgeMillauMessages declares internal migrations (which *might* execute), setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for DynamicFee, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Ethereum, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for EVM, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for TronBacking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for EthereumRelayAuthorities, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for EthereumRelayerGame, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for EthereumIssuing, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for EthereumBacking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for EthereumRelay, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for CrabBacking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for CrabIssuing, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Multisig, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Proxy, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Scheduler, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Recovery, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Society, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Identity, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Utility, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Vesting, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Claims, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Sudo, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Treasury, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for TechnicalMembership, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for PhragmenElection, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for TechnicalCommittee, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Council, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Democracy, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for HeaderMMR, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for AuthorityDiscovery, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for ImOnline, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Grandpa, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Session, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Historical, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ⚠️ Offences declares internal migrations (which *might* execute), setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 have 0 deferred offences, applying.    
2021-07-27 16:54:24 ✅ no migration for Staking, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for ElectionProviderMultiPhase, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Authorship, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for TransactionPayment, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Kton, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Balances, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Timestamp, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for Babe, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ✅ no migration for RandomnessCollectiveFlip, setting storage version to <wasm:stripped>    
2021-07-27 16:54:24 ⚠️  Dropping non-mandatory inherent from overweight block.    
2021-07-27 16:54:24 🎁 Prepared block for proposing at 16 [hash: 0x9719a51bd745f560ed5b2180f973d499d1afdc4d32bcd78a8be123d3e78c492e; parent_hash: 0x9d26…d212; extrinsics (1): [0x3b61…b011]]    
2021-07-27 16:54:24 🔖 Pre-sealed block for proposal at 16. Hash now 0xfb5ff08f9525eb57548081cacd5af85d3602f024e0155eee0dcfac8ab81e34f5, previously 0x9719a51bd745f560ed5b2180f973d499d1afdc4d32bcd78a8be123d3e78c492e.    
2021-07-27 16:54:24 ✨ Imported #16 (0xfb5f…34f5)    
2021-07-27 16:54:26 💤 Idle (0 peers), best: #16 (0xfb5f…34f5), finalized #13 (0x5b5c…334d), ⬇ 0 ⬆ 0    
2021-07-27 16:54:30 🙌 Starting consensus session on top of parent 0xfb5ff08f9525eb57548081cacd5af85d3602f024e0155eee0dcfac8ab81e34f5    
2021-07-27 16:54:30 🎁 Prepared block for proposing at 17 [hash: 0x40ffa937c825337cf44bdb211ef56a3ff9e9dd9e596cf7a15122577f83cf6594; parent_hash: 0xfb5f…34f5; extrinsics (2): [0x8223…b361, 0x42a6…4e6e]]    
2021-07-27 16:54:30 🔖 Pre-sealed block for proposal at 17. Hash now 0x263d575f9a791bbacf6e2673ed0d000afbb99404fcc4459e536d78cc3c054039, previously 0x40ffa937c825337cf44bdb211ef56a3ff9e9dd9e596cf7a15122577f83cf6594.    
2021-07-27 16:54:30 ✨ Imported #17 (0x263d…4039)
```

**Comment by HackFisher** [comment]
> We might need to include London Hardfork changes in v0.11.1 if substrate dep ([darwinia-v0.11.2](https://github.com/darwinia-network/substrate/tree/darwinia-v0.11.2)) will require mandatory upgrade for nodes.

The hint was from https://github.com/paritytech/polkadot/releases/tag/v0.9.2, and related to https://github.com/paritytech/substrate/pull/8688, we might need to learn more of it and test again using fork off before production runtime upgrade, just in case it depend on chain state and context.

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
