### PR TITLE
Release S2S Beta.1

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Need to check the parity-bridges-common's storage changes from June 7 5a9862f33d3a2aa0bd8f26d12f630cd126ae6c70

@xiaoch05

**Comment by AurevoirXavier** [comment]
Looks like there are no storage changes from upstream. From my review.

**Review by HackFisher — APPROVED** [review]
No storage related changes in 

modules/grandpa/src/lib.rs

https://github.com/paritytech/parity-bridges-common/compare/5a9862f33d3a2aa0bd8f26d12f630cd126ae6c70...master

**Comment by AurevoirXavier** [comment]
> No storage related changes in
> 
> modules/grandpa/src/lib.rs
> 
> [paritytech/parity-bridges-common@5a9862f...master](https://github.com/paritytech/parity-bridges-common/compare/5a9862f33d3a2aa0bd8f26d12f630cd126ae6c70...master)

Also, need to check dispatch/message pallet

**Comment by HackFisher** [comment]
Do we need to check dispatch and message, if the ci (Check storage prefix) didn't print diffs?

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-common/blob/1ba8024c99d631e6723fa248824dd39fb9b48f59/node/runtime/pangolin/src/lib.rs#L279

This should be named as `BridgeDispatch` instead ?

Refer: https://github.com/paritytech/parity-bridges-common/blob/0791e911c1b8e97148ddaf2cfa21641917b89cb9/bin/rialto/runtime/src/lib.rs#L561

**Comment by AurevoirXavier** [comment]
> Do we need to check dispatch and message, if the ci (Check storage prefix) didn't print diffs?

Nope.

But I've checked them manually for better security.

**Comment by AurevoirXavier** [comment]
> https://github.com/darwinia-network/darwinia-common/blob/1ba8024c99d631e6723fa248824dd39fb9b48f59/node/runtime/pangolin/src/lib.rs#L279
> 
> This should be named as `BridgeDispatch` instead ?
> 
> Refer: https://github.com/paritytech/parity-bridges-common/blob/0791e911c1b8e97148ddaf2cfa21641917b89cb9/bin/rialto/runtime/src/lib.rs#L561

@xiaoch05 Do we need multi-dispatch instance?

**Comment by HackFisher** [comment]
> @xiaoch05 Do we need multiple dispatch instances?

I think dispatch pallet support multi chains by default, and it is used for self runtime, so no need for multiple instances IMO.

**Comment by HackFisher** [comment]
> > Do we need to check dispatch and message, if the ci (Check storage prefix) didn't print diffs?
> 
> Nope.
> 
> But I've checked them manually for better security.

Why the ci(check storage prefix) didn't print prefix related to `bridgeMillauMessage`? Or it will not print if if found the related storages are empty?

**Comment by AurevoirXavier** [comment]
> > > Do we need to check dispatch and message, if the ci (Check storage prefix) didn't print diffs?
> > 
> > 
> > Nope.
> > But I've checked them manually for better security.
> 
> Why the ci(check storage prefix) didn't print prefix related to `bridgeMillauMessage`? Or it will not print if if found the related storages value items are empty?

That is a pallet-level change.
CI regards that pallet as a new pallet. Nothing to be compared with.

**Comment by xiaoch05** [comment]
> > @xiaoch05 Do we need multiple dispatch instances?
> 
> I think dispatch pallet support multi chains by default, and it is used for self runtime, so no need for multiple instances IMO.

Also I think we don't need. The target chain use a common dispatcher to dispatch messages to different pallets by the message payload(call)

**Comment by AurevoirXavier** [comment]
> > > Do we need to check dispatch and message, if the ci (Check storage prefix) didn't print diffs?
> > 
> > 
> > Nope.
> > But I've checked them manually for better security.
> 
> Why the ci(check storage prefix) didn't print prefix related to `bridgeMillauMessage`? Or it will not print if if found the related storages value items are empty?

~~That is a pallet-level change.~~
~~CI regards that pallet as a new pallet. Nothing to be compared with.~~
~~So, I skipped the item checks currently.~~


Because it still using FrameV1
```
decl_storage! {
	trait Store for Pallet<T: Config<I>, I: Instance = DefaultInstance> as BridgeMessages {
```

**Comment by AurevoirXavier** [comment]
```
2021-08-30 18:17:51 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2021-08-30 18:17:51 [#0] 🗳  Finalized election round with compute ElectionCompute::OnChain.    
2021-08-30 18:17:51 [0] 💸 new validator set of size 1 has been processed for era 1    
2021-08-30 18:17:51 [darwinia-claims] Genesis Claims List is Set to EMPTY    
2021-08-30 18:17:51 initializing remote client to "http://t2.pangolin-p2p.darwinia.network"    
2021-08-30 18:17:51 scraping keypairs from remote node http://t2.pangolin-p2p.darwinia.network @ 0xf921ec63e249420d5487fab3d521c6ab3bfec1ee2141ac876682e93725a1d721    
2021-08-30 18:17:51 downloading data for all modules.    
2021-08-30 18:17:57 extending externalities with 1 manually injected keys    
2021-08-30 18:17:57 injecting a total of 3270 keys    
2021-08-30 18:17:57 ⚠️ System declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for BSC, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Substrate2SubstrateIssuing, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for BridgePangoroGrandpa, setting storage version to PalletVersion { major: 0, minor: 1, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for BridgeDispatch, setting storage version to PalletVersion { major: 0, minor: 1, patch: 0 }    
2021-08-30 18:17:57 ⚠️ BridgePangoroMessages declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 0, minor: 1, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for DynamicFee, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Ethereum, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for EVM, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for TronBacking, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for EthereumRelayAuthorities, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for EthereumRelayerGame, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for EthereumIssuing, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for EthereumBacking, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for EthereumRelay, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for CrabBacking, setting storage version to PalletVersion { major: 2, minor: 5, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for CrabIssuing, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Multisig, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Proxy, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Scheduler, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Recovery, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Society, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Identity, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Utility, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Vesting, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Claims, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Sudo, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Bounties, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Tips, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for KtonTreasury, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Treasury, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for TechnicalMembership, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for PhragmenElection, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for TechnicalCommittee, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Council, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Democracy, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for HeaderMMR, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for AuthorityDiscovery, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for ImOnline, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Grandpa, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Session, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Historical, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ⚠️ Offences declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 have 0 deferred offences, applying.    
2021-08-30 18:17:57 ✅ no migration for Staking, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for ElectionProviderMultiPhase, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Authorship, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for TransactionPayment, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Kton, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Balances, setting storage version to PalletVersion { major: 2, minor: 6, patch: 2 }    
2021-08-30 18:17:57 ✅ no migration for Timestamp, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for Babe, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 ✅ no migration for RandomnessCollectiveFlip, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-08-30 18:17:57 try-runtime executed without errors. Consumed weight = 513369600000000, total weight = 512000000000000 (1.002675)
```

**Pull request merged**
