### PR TITLE
Upgrade EVM pallet to FRAMEv2

### PR DESCRIPTION
**Pull request by AsceticBear**
The old version metadata:

```sh
$ subsee -p EVM > evm_old.json

{"name":"EVM","storage":{"prefix":"EVM","entries":[{"name":"AccountCodes","modifier":"Default","ty":{"Map":{"hasher":"Blake2_128Concat","key":"H160","value":"Vec<u8>","unused":false}},"default":[0],"documentation":[]},{"name":"AccountStorages","modifier":"Default","ty":{"DoubleMap":{"hasher":"Blake2_128Concat","key1":"H160","key2":"H256","value":"H256","key2_hasher":"Blake2_128Concat"}},"default":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"documentation":[]}]},"calls":[{"name":"call","arguments":[{"name":"source","ty":"H160"},{"name":"target","ty":"H160"},{"name":"input","ty":"Vec<u8>"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Option<U256>"}],"documentation":[" Issue an EVM call operation. This is similar to a message call transaction in Ethereum."]},{"name":"create","arguments":[{"name":"source","ty":"H160"},{"name":"init","ty":"Vec<u8>"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Option<U256>"}],"documentation":[" Issue an EVM create operation. This is similar to a contract creation transaction in"," Ethereum."]},{"name":"create2","arguments":[{"name":"source","ty":"H160"},{"name":"init","ty":"Vec<u8>"},{"name":"salt","ty":"H256"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Option<U256>"}],"documentation":[" Issue an EVM create2 operation."]}],"event":[{"name":"Log","arguments":["Log"],"documentation":[" Ethereum events from contracts."]},{"name":"Created","arguments":["H160"],"documentation":[" A contract has been created at given \\[address\\]."]},{"name":"CreatedFailed","arguments":["H160"],"documentation":[" A \\[contract\\] was attempted to be created, but the execution failed."]},{"name":"Executed","arguments":["H160"],"documentation":[" A \\[contract\\] has been executed successfully with states applied."]},{"name":"ExecutedFailed","arguments":["H160"],"documentation":[" A \\[contract\\] has been executed with errors. States are reverted with only gas fees applied."]},{"name":"BalanceDeposit","arguments":["AccountId","H160","U256"],"documentation":[" A deposit has been made at a given address. \\[sender, address, value\\]"]},{"name":"BalanceWithdraw","arguments":["AccountId","H160","U256"],"documentation":[" A withdrawal has been made from a given address. \\[sender, address, value\\]"]}],"constants":[],"errors":[{"name":"BalanceLow","documentation":[" Not enough balance to perform action"]},{"name":"FeeOverflow","documentation":[" Calculating total fee overflowed"]},{"name":"PaymentOverflow","documentation":[" Calculating total payment overflowed"]},{"name":"WithdrawFailed","documentation":[" Withdraw fee failed"]},{"name":"GasPriceTooLow","documentation":[" Gas price is too low."]},{"name":"InvalidNonce","documentation":[" Nonce is invalid"]}],"index":40}
```

the new version metadata after upgrade:

```sh
$ subsee -p EVM > evm_new.json

{"name":"EVM","storage":{"prefix":"EVM","entries":[{"name":"AccountCodes","modifier":"Default","ty":{"Map":{"hasher":"Blake2_128Concat","key":"H160","value":"Vec<u8>","unused":false}},"default":[0],"documentation":[]},{"name":"AccountStorages","modifier":"Default","ty":{"DoubleMap":{"hasher":"Blake2_128Concat","key1":"H160","key2":"H256","value":"H256","key2_hasher":"Blake2_128Concat"}},"default":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"documentation":[]}]},"calls":[{"name":"call","arguments":[{"name":"source","ty":"H160"},{"name":"target","ty":"H160"},{"name":"input","ty":"Vec<u8>"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Option<U256>"}],"documentation":[" Issue an EVM call operation. This is similar to a message call transaction in Ethereum."]},{"name":"create","arguments":[{"name":"source","ty":"H160"},{"name":"init","ty":"Vec<u8>"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Option<U256>"}],"documentation":[" Issue an EVM create operation. This is similar to a contract creation transaction in"," Ethereum."]},{"name":"create2","arguments":[{"name":"source","ty":"H160"},{"name":"init","ty":"Vec<u8>"},{"name":"salt","ty":"H256"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Option<U256>"}],"documentation":[" Issue an EVM create2 operation."]}],"event":[{"name":"Log","arguments":["Log"],"documentation":[" Ethereum events from contracts."]},{"name":"Created","arguments":["H160"],"documentation":[" A contract has been created at given \\[address\\]."]},{"name":"CreatedFailed","arguments":["H160"],"documentation":[" A \\[contract\\] was attempted to be created, but the execution failed."]},{"name":"Executed","arguments":["H160"],"documentation":[" A \\[contract\\] has been executed successfully with states applied."]},{"name":"ExecutedFailed","arguments":["H160"],"documentation":[" A \\[contract\\] has been executed with errors. States are reverted with only gas fees applied."]},{"name":"BalanceDeposit","arguments":["AccountId","H160","U256"],"documentation":[" A deposit has been made at a given address. \\[sender, address, value\\]"]},{"name":"BalanceWithdraw","arguments":["AccountId","H160","U256"],"documentation":[" A withdrawal has been made from a given address. \\[sender, address, value\\]"]}],"constants":[],"errors":[{"name":"BalanceLow","documentation":[" Not enough balance to perform action"]},{"name":"FeeOverflow","documentation":[" Calculating total fee overflowed"]},{"name":"PaymentOverflow","documentation":[" Calculating total payment overflowed"]},{"name":"WithdrawFailed","documentation":[" Withdraw fee failed"]},{"name":"GasPriceTooLow","documentation":[" Gas price is too low."]},{"name":"InvalidNonce","documentation":[" Nonce is invalid"]}],"index":40}
```

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Is there a companion PR from upstream?

**Comment by AsceticBear** [comment]
> Is there a companion PR from upstream?

Not exactly. There is a merged pr in upstream https://github.com/paritytech/frontier/pull/380.  Since there are some subtle differences between darwinia-evm and upstream evm pallet, so I upgraded this pallet by myself following guidelines.

**Review by HackFisher — APPROVED** [review]
Runtimes are using the same pallet prefix "EVM".

LGTM

**Comment by HackFisher** [comment]
@AurevoirXavier Please help review this pull request

**Review by AurevoirXavier — APPROVED** [review]

**Pull request merged**
