### PR TITLE
Substrate Update

### PR DESCRIPTION
**Pull request by AurevoirXavier**
https://github.com/darwinia-network/substrate-update-tracking/issues/17

### CODE REVIEW

**Comment by HackFisher** [comment]
There are Conflicting files

**Review by HackFisher — COMMENTED** [review]
@WoeOm Please check and whether we need companion PR for darwinia.js?

According to https://github.com/darwinia-network/darwinia/wiki/Darwinia-Dependency-Upgrade-and-Communication-Convention

**Comment by WoeOm** [comment]
Has this modification been deployed to pangolin or dev? Need to test the runtime

**Comment by HackFisher** [comment]
To minimize the requirement of communication and dependency between developer, I think it will be great and important if the darwinia.js and apps developers can setup a local devnet following this branch and document by themselves.

**Comment by AurevoirXavier** [comment]
> Has this modification been deployed to pangolin or dev? Need to test the runtime

Once it merged. It will be deployed to Pangolin.

**Comment by HackFisher** [comment]
apps and darwinia.js should be ready and upgraded before the runtime upgrade, so I think we should use pangolin-dev for testing IMO.

**Comment by HackFisher** [comment]
> Those changes look good to me. But, I suggest updating the spec version in a separate pull request in future development. 
> 
> 
> 
> Separate functionality change and release change will make other developers easily choose the version and testing.

I do not like this practice becuase forgot to bump spec vesion could cause serious network fork if we forget to do that later.(Who knows).

This makes security audit difficult, we must consider the security in the deplyment process and conversation.

**Review by AsceticBear — APPROVED** [review]

**Comment by HackFisher** [comment]
@AurevoirXavier There are conflicts.

**Comment by WoeOm** [comment]
Check List: 
- [x] Apps 
- [x] darwinia.js

**Review by HackFisher — APPROVED** [review]
LGTM.

Good to go after @WoeOm check the changes in latest commits.

**Comment by WoeOm** [comment]
> LGTM.
> 
> Good to go after @WoeOm check the changes in latest commits.

No new errors were found after passing the test.

**Pull request merged**
