### PR TITLE
Change name of mmr root to parent mmr root, related #380

### PR DESCRIPTION
**Pull request by HackFisher**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Should we change `pub mmr_root: Hash`, to `pub parent_mmr_root: Hash`

```rust
pub struct MerkleMountainRangeRootLog<Hash> {
	/// Specific prefix to identify the mmr root log in the digest items with Other type.
	pub prefix: [u8; 4],
	/// The merkle mountain range root hash.
	pub mmr_root: Hash,
}
```

**Comment by HackFisher** [comment]
> Should we change `pub mmr_root: Hash` to `pub parent_mmr_root: Hash`
> 
> ```rust
> pub struct MerkleMountainRangeRootLog<Hash> {
> 	/// Specific prefix to identify the mmr root log in the digest items with Other type.
> 	pub prefix: [u8; 4],
> 	/// The merkle mountain range root hash.
> 	pub mmr_root: Hash,
> }
> ```

MerkleMountainRangeRootLog is a common struct, and has no directly connection to business meanings, so I was going to keep it as it is.

Another concern I want to confirm is: Changing the field of the struct will not affect storage codec, right?

**Comment by AurevoirXavier** [comment]
> > Should we change `pub mmr_root: Hash` to `pub parent_mmr_root: Hash`
> > ```rust
> > pub struct MerkleMountainRangeRootLog<Hash> {
> > 	/// Specific prefix to identify the mmr root log in the digest items with Other type.
> > 	pub prefix: [u8; 4],
> > 	/// The merkle mountain range root hash.
> > 	pub mmr_root: Hash,
> > }
> > ```
> 
> MerkleMountainRangeRootLog is a common struct, and has no directly connection to business meanings, so I was going to keep it as it is.
> 
> Another concern I want to confirm is: Changing the field of the struct will not affect storage codec, right?

Yes, it won't. 

But if we use this struct in front-end or somewhere, it'll show `mmr_root`, but actually, it stores the `parent_mmr_root`

**Comment by HackFisher** [comment]
> ```rust
> mmr_root
> ```

I changed `mmr_root` in the struct to `parent_mmr_root`.

**Review by AurevoirXavier — APPROVED** [review]

**Pull request merged**
