### PR TITLE
BEEFY integration

### PR DESCRIPTION
**Pull request by hujw77**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Need help?

**Comment by HackFisher** [comment]
@hujw77 @xiaoch05 Prefer to use https://github.com/paritytech/grandpa-bridge-gadget (Or its fork if necessary) as dependency instead of copy to the common here.

**Comment by hujw77** [comment]
> Need help?

https://github.com/paritytech/substrate/blob/287b5c5a8fe47beacfdfdf764b632b897691e9da/primitives/core/src/ecdsa.rs#L576
BEEFY use this function to verify sign, It needs the latest substrate version, Darwinia's substrate lib may need to upgrade.

**Comment by hujw77** [comment]
> @hujw77 @xiaoch05 Prefer to use https://github.com/paritytech/grandpa-bridge-gadget (Or its fork if necessary) as dependency instead of copy to the common here.

OK

**Comment by AurevoirXavier** [comment]
We fall behind the latest substrate code around 5-6 times runtime upgrade

**Comment by AurevoirXavier** [comment]
Move to https://github.com/darwinia-network/darwinia-common/tree/xavier-beefy

**Pull request closed without merging**
