### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by AurevoirXavier**
- [x] Handle multiple pallets under a common prefix.
- [x] Check `spec_version`.
- [ ] ~~Try runtime.~~

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
>> Release ${{ github.sha }}
            
            ## Check runtime version:
            ```diff
            ${{ steps.check-runtime-version.outputs.check-runtime-version }}
            ```

            ## Check storage prefix:
            ```diff`
            ${{ steps.check-storage-prefix.outputs.check-storage-prefix }}
            ```

**Comment by AurevoirXavier** [comment]
@HackFisher @wi1dcard  Please review

**Review by wi1dcard — APPROVED** [review]

**Review by HackFisher — APPROVED** [review]

**Comment by HackFisher** [comment]
> > **Check Storage Prefix**
> 
> ```diff
> Pallet: DarwiniaStaking:
> - 	Item: Storage { name: "ModifiedValidatorCount", type: Plain("u32") }
> + 	Item: Storage { name: "ValidatorCount", type: Plain("u32") }​
> ```
> 
> > SHA [8c7115e](https://github.com/darwinia-network/darwinia-common/commit/8c7115efe2c73666f5178cd35cbd80c91117b100)


The diff there is incorrect? It seems to be expected as exactly opposite way?
> ```diff
> Pallet: DarwiniaStaking:
> - 	Item: Storage { name: "ValidatorCount", type: Plain("u32") }​
> + 	Item: Storage { name: "ModifiedValidatorCount", type: Plain("u32") }
> ```

**Comment by AurevoirXavier** [comment]
> The diff there is incorrect? It seems to be expected as exactly opposite way?

Yes, I just updated the checker.

**Pull request merged**
