### PR TITLE
Rename

### PR DESCRIPTION
**Pull request by AurevoirXavier**
`parity-bridges-common` to `darwinia-bridges-substrate`

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Looks like DVM tests failed. 
cc @AsceticBear

**Comment by AsceticBear** [comment]
image

Update Node version to fix it.

**Comment by fewensa** [comment]
The darwinia-v0.12.0 branch also needs this update

**Review by HackFisher — APPROVED** [review]

**Comment by HackFisher** [comment]
For github, the old name `parity-bridges-common` should be still available if no overwrites, so renaming is optional for now?

**Comment by fewensa** [comment]
> For github, the old name `parity-bridges-common` should be still available if no new overwrites, so downstream renaming is optional for now?

No, It's failed to build for dariwnia-crab bridge


https://github.com/darwinia-network/bridger/pull/433/commits/724516ca3121e9fa0fd07d0b4f2117cf1ec01237

https://github.com/darwinia-network/bridger/blob/724516ca3121e9fa0fd07d0b4f2117cf1ec01237/bridges/darwinia-crab/Cargo.lock#L752-L765


```
error[E0599]: no function or associated item named `max_extrinsic_size` found for struct `darwinia_runtime::Darwinia` in the current scope
  --> client-darwinia\src\darwinia.rs:38:47
   |
38 |         darwinia_bridge_primitives::Darwinia::max_extrinsic_size()
   |                                               ^^^^^^^^^^^^^^^^^^ function or associated item not found in `darwinia_runtime::Darwinia`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use bp_runtime::chain::Chain;
   |

error[E0599]: no function or associated item named `max_extrinsic_weight` found for struct `darwinia_runtime::Darwinia` in the current scope
  --> client-darwinia\src\darwinia.rs:42:47
   |
42 |         darwinia_bridge_primitives::Darwinia::max_extrinsic_weight()
   |                                               ^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `darwinia_runtime::Darwinia`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use bp_runtime::chain::Chain;
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `client-darwinia` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Pull request merged**
