### PR TITLE
remove unused feature

### PR DESCRIPTION
**Pull request by xiaoch05**

### CODE REVIEW

**Review by HackFisher — APPROVED** [review]

**Review by AurevoirXavier — CHANGES_REQUESTED** [review]
Why? https://github.com/rust-blockchain/ethereum/blob/master/Cargo.toml#L35

**Comment by AurevoirXavier** [comment]
And we also need the `ethereum/std { scale-info/std }` in the future.

**Comment by xiaoch05** [comment]
> Why? https://github.com/rust-blockchain/ethereum/blob/master/Cargo.toml#L35

This pallet only use it as dev dependency

**Comment by AurevoirXavier** [comment]
So remove the `default-features = false` ethier.

**Comment by AurevoirXavier** [comment]
Why the lock file changed?

**Comment by xiaoch05** [comment]
> Why the lock file changed?

I'm not sure. The ethereum feature changed impact evm package?

**Comment by HackFisher** [comment]
> > Why the lock file changed?
> 
> I'm not sure. The ethereum feature changed impact evm package?

std will require serde? @AurevoirXavier Please review and merge this.

**Pull request merged**
