### PR TITLE
fix millau types

### PR DESCRIPTION
**Pull request by fewensa**
with

https://github.com/darwinia-network/darwinia-launch/commit/cdd1d662cd665600cc71e6db14f66281f70381f4

### CODE REVIEW

**Comment by AsceticBear** [comment]
I suggest removing the `bp-millau` direct dependency from the upstream repo and put the content into common node primitives.

**Comment by AsceticBear** [comment]
Done this change related to the `substrate-relay` build client error?

```sh
2021-06-17T09:36:39Z INFO  chain_relay::s2s::init_bridge] Init bridge MillauToPangolin
[2021-06-17T09:36:39Z DEBUG chain_relay::s2s::init_bridge] source -> ChainInfo { host: "127.0.0.1", port: 9945, signer: None, secure: false, signer_password: None }
[2021-06-17T09:36:39Z DEBUG chain_relay::s2s::init_bridge] target -> ChainInfo { host: "127.0.0.1", port: 9944, signer: Some("//Alice"), secure: false, signer_password: None }
[2021-06-17T09:36:39Z ERROR relay_substrate_client::client] Failed to connect to Millau node: RpcError(ParseError(Error("invalid length 64, expected a 0x-prefixed hex string with length of 128", line: 0, column: 0))). Going to retry in 10s

```

**Comment by fewensa** [comment]
I think so, I will join the plan to remove `bp_millau`.
Yes, fix this error, substrate-relay also need to be modify

**Comment by AsceticBear** [comment]
> I think so, I will join the plan to remove `bp_millau`.

It is possible to finish this remove in this pr?

**Comment by fewensa** [comment]
I'll check it, Still in use in some places in multiple project
https://github.com/darwinia-network/darwinia-launch/blob/ef6b9aeec544273c1e01d2a2dc9b416c0962d5b3/millau/runtime/src/pangolin_messages.rs#L123
https://github.com/darwinia-network/darwinia-launch/blob/ef6b9aeec544273c1e01d2a2dc9b416c0962d5b3/millau/runtime/src/pangolin_messages.rs#L129
https://github.com/darwinia-network/darwinia-launch/blob/ef6b9aeec544273c1e01d2a2dc9b416c0962d5b3/millau/runtime/src/pangolin_messages.rs#L139
https://github.com/darwinia-network/darwinia-common/blob/9f0209b691ec9abb7406576156f9ea4616cceab8/bin/node/runtime/pangolin/src/bridges/substrate/millau_messages.rs#L126

**Comment by fewensa** [comment]
We need to keep `bp_millau`

have some trait implement to Runtime

https://github.com/darwinia-network/darwinia-common/blob/9f0209b691ec9abb7406576156f9ea4616cceab8/bin/node/runtime/pangolin/src/lib.rs#L806-L818

If we remove it, we should be create a new crate to add these traits. in Pnaoglin it's defined in https://github.com/darwinia-network/darwinia-common/blob/master/bin/node/bridge-primitives/pangolin/src/lib.rs

**Comment by fewensa** [comment]
ok,we must do this, happen some error.

```
error[E0053]: method `best_finalized` has an incompatible type for trait
     --> D:\dev\darwinia-network\darwinia-common\bin\node\runtime\pangolin\src\lib.rs:757:3
      |
  757 |         fn best_finalized() -> (drml_primitives::BlockNumber, drml_primitives::Hash) {
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found `u32`
      |
      = note: expected fn pointer `fn() -> (u64, MillauHash)`
                 found fn pointer `fn() -> (u32, H256)`
```


https://github.com/darwinia-network/parity-bridges-common/blob/b9545dcb66da4ea572c9c43959cf088f2047a2c5/primitives/chain-millau/src/lib.rs#L267-L270

😢

**Pull request closed without merging**
