### PR TITLE
Generic account basic

### PR DESCRIPTION
**Pull request by AsceticBear**
This PR is the first step for #575. It would be much clear to hack precompile after this generic refactor.

### CODE REVIEW

**Review by HackFisher — APPROVED** [review]

**Comment by AsceticBear** [comment]
@AurevoirXavier  Need your review also.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier Need your review also.

Ing

**Review by AurevoirXavier — CHANGES_REQUESTED** [review]
The implementation looks not good. Too many dup def.

I'm going to refactor this.

E.g

```
type RingCurrency = Ring;
type RingAccountBasic = DvmAccountBasic<Self, Ring, RingRemainBalance>;
                                              ^^^^ just Self::RingCurrency                                    
```

**Comment by AsceticBear** [comment]
> I'm going to refactor this.

Go and make it better.

**Comment by AurevoirXavier** [comment]
After I reading evm codes. I found it's not easy to apply the refactor. And don't want to make too much breaking changes.

Do you think is good to use a custom `Basic` instead evm's?

```rust
Basic {
	balance,
	nonce,
}

// ---

Basic {
	ring,
	kton,
	nonce,
}
```

**Review by AurevoirXavier — APPROVED** [review]

**Comment by AsceticBear** [comment]
> After I reading the evm codes. I found it's not easy to apply the refactoring. And I don't want to introduce too much breaking changes.
> 
> BTW, do you think is good to use a custom `Basic` instead evm's?
> 
> ```rust
> Basic {
> 	balance,
> 	nonce,
> }
> 
> // ---
> 
> Basic {
> 	ring,
> 	kton,
> 	nonce,
> }
> ```

I do not think this is a good idea. Because only `RING` will be consumed during evm execution.

The `KtonAccountBasic` is designed to purely handle issues about Kton precompile.

**Pull request merged**
