### PR TITLE
Release v2.7.1

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by HackFisher** [comment]
It looks like that some old migration codes are not removed yet, and we may need some new migrations code according to the output of `Check Storage Prefix`?

**Comment by HackFisher** [comment]
> 
> > Check Storage Prefix
> 
> ```diff
> Pallet Identity:
> + 	Item: Storage { name: "IdentityOf", type: Map { hasher: Twox64Concat, key: "T::AccountId", value: "Registration<BalanceOf<T>, T::MaxRegistrars, T::MaxAdditionalFields>", unused: false } }
> - 	Item: Storage { name: "IdentityOf", type: Map { hasher: Twox64Concat, key: "T::AccountId", value: "Registration<BalanceOf<T>>", unused: false } }
> + 	Item: Storage { name: "Registrars", type: Plain("BoundedVec<Option<RegistrarInfo<BalanceOf<T>, T::AccountId>>, T\n::MaxRegistrars>") }
> - 	Item: Storage { name: "Registrars", type: Plain("Vec<Option<RegistrarInfo<BalanceOf<T>, T::AccountId>>>") }
> + 	Item: Storage { name: "SubsOf", type: Map { hasher: Twox64Concat, key: "T::AccountId", value: "(BalanceOf<T>, BoundedVec<T::AccountId, T::MaxSubAccounts>)", unused: false } }
> - 	Item: Storage { name: "SubsOf", type: Map { hasher: Twox64Concat, key: "T::AccountId", value: "(BalanceOf<T>, Vec<T::AccountId>)", unused: false } }
> 


Do we need to do migration for pallet Identity, or upstream substrate will automatically do this for us? Or essentially, there is not type storage definition change, only generic and name changes?

**Comment by AurevoirXavier** [comment]
> Do we need to do migration for pallet Identity, or upstream substrate will automatically do this for us? Or essentially, there is not type storage definition change, only generic and name changes?

Just like before, from `Vec` to `BoundedVec`.
No need to migrate.

**Review by HackFisher — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
## Pangoro Try Runtime
```
2021-12-08 11:53:11 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2021-12-08 11:53:11 [0] 💸 new validator set of size 1 has been processed for era 1    
2021-12-08 11:53:11 initializing remote client to "wss://pangoro-rpc.darwinia.network"    
2021-12-08 11:53:12 scraping key-pairs from remote @ 0x185161337ee67e0450700f7259076e37d0328be5835cff9a5c8209d1081ad9c7    
2021-12-08 11:53:12 downloading data for all modules.    
2021-12-08 11:53:45 Querying a total of 7370 keys    
2021-12-08 11:54:09 extending externalities with 1 manually injected key-values    
2021-12-08 11:54:09 injecting a total of 7372 keys    
2021-12-08 11:54:09 ⚠️ System declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-08 11:54:09 ✅ no migration for TransactionPause    
2021-12-08 11:54:09 ✅ no migration for FeeMarket    
2021-12-08 11:54:09 ✅ no migration for Substrate2SubstrateBacking    
2021-12-08 11:54:09 ✅ no migration for BridgePangolinMessages    
2021-12-08 11:54:09 ✅ no migration for BridgePangolinGrandpa    
2021-12-08 11:54:09 ✅ no migration for BridgePangolinDispatch    
2021-12-08 11:54:09 ✅ no migration for Scheduler    
2021-12-08 11:54:09 ✅ no migration for Sudo    
2021-12-08 11:54:09 ✅ no migration for Treasury    
2021-12-08 11:54:09 ✅ no migration for AuthorityDiscovery    
2021-12-08 11:54:09 ✅ no migration for ImOnline    
2021-12-08 11:54:09 ✅ no migration for Grandpa    
2021-12-08 11:54:09 ✅ no migration for Session    
2021-12-08 11:54:09 ✅ no migration for Historical    
2021-12-08 11:54:09 ⚠️ Offences declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-08 11:54:09 have 0 deferred offences, applying.    
2021-12-08 11:54:09 ⚠️ Staking declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-08 11:54:09 [127248] 💸 Migrating staking to Releases::V7_0_0    
2021-12-08 11:54:09 [127248] 💸 Completed staking migration to Releases::V7_0_0    
2021-12-08 11:54:09 ✅ no migration for ElectionProviderMultiPhase    
2021-12-08 11:54:09 ✅ no migration for Authorship    
2021-12-08 11:54:09 ✅ no migration for TransactionPayment    
2021-12-08 11:54:09 ✅ no migration for Kton    
2021-12-08 11:54:09 ✅ no migration for Balances    
2021-12-08 11:54:09 ✅ no migration for Timestamp    
2021-12-08 11:54:09 ✅ no migration for Babe    
2021-12-08 11:54:09 ✅ no migration for RandomnessCollectiveFlip    
2021-12-08 11:54:09 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 121600000000, total weight = 512000000000000 (0.0002375)
```

## Pangolin Try Runtime
```
2021-12-08 11:54:05 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2021-12-08 11:54:05 [0] 💸 new validator set of size 1 has been processed for era 1    
2021-12-08 11:54:05 [darwinia-claims] Genesis Claims List is Set to EMPTY    
2021-12-08 11:54:05 initializing remote client to "wss://pangolin-rpc.darwinia.network"    
2021-12-08 11:54:06 scraping key-pairs from remote @ 0x551c57a3cde52824a2fa348c4631b81baa656f353ce343b35ba99aa29e065a75    
2021-12-08 11:54:06 downloading data for all modules.    
2021-12-08 11:54:26 Querying a total of 11159 keys    
2021-12-08 11:54:41 extending externalities with 1 manually injected key-values    
2021-12-08 11:54:41 injecting a total of 11161 keys    
2021-12-08 11:54:42 `KtonTreasury` migrated.    
2021-12-08 11:54:42 ⚠️ System declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-08 11:54:42 ✅ no migration for TransactionPause    
2021-12-08 11:54:42 ✅ no migration for FeeMarket    
2021-12-08 11:54:42 ✅ no migration for BSC    
2021-12-08 11:54:42 ✅ no migration for Substrate2SubstrateIssuing    
2021-12-08 11:54:42 ✅ no migration for BridgePangoroMessages    
2021-12-08 11:54:42 ✅ no migration for BridgePangoroGrandpa    
2021-12-08 11:54:42 ✅ no migration for BridgePangoroDispatch    
2021-12-08 11:54:42 ✅ no migration for Ethereum    
2021-12-08 11:54:42 ✅ no migration for EVM    
2021-12-08 11:54:42 ✅ no migration for TronBacking    
2021-12-08 11:54:42 ✅ no migration for EthereumRelayAuthorities    
2021-12-08 11:54:42 ✅ no migration for EthereumRelayerGame    
2021-12-08 11:54:42 ✅ no migration for EthereumIssuing    
2021-12-08 11:54:42 ✅ no migration for EthereumBacking    
2021-12-08 11:54:42 ✅ no migration for EthereumRelay    
2021-12-08 11:54:42 ✅ no migration for Multisig    
2021-12-08 11:54:42 ✅ no migration for Proxy    
2021-12-08 11:54:42 ✅ no migration for Scheduler    
2021-12-08 11:54:42 ✅ no migration for Recovery    
2021-12-08 11:54:42 ✅ no migration for Society    
2021-12-08 11:54:42 ✅ no migration for Identity    
2021-12-08 11:54:42 ✅ no migration for Utility    
2021-12-08 11:54:42 ✅ no migration for Vesting    
2021-12-08 11:54:42 ✅ no migration for Claims    
2021-12-08 11:54:42 ✅ no migration for Sudo    
2021-12-08 11:54:42 ✅ no migration for Bounties    
2021-12-08 11:54:42 ✅ no migration for Tips    
2021-12-08 11:54:42 ✅ no migration for KtonTreasury    
2021-12-08 11:54:42 ✅ no migration for Treasury    
2021-12-08 11:54:42 ✅ no migration for TechnicalMembership    
2021-12-08 11:54:42 ✅ no migration for PhragmenElection    
2021-12-08 11:54:42 ✅ no migration for TechnicalCommittee    
2021-12-08 11:54:42 ✅ no migration for Council    
2021-12-08 11:54:42 ✅ no migration for Democracy    
2021-12-08 11:54:42 ✅ no migration for HeaderMMR    
2021-12-08 11:54:42 ✅ no migration for AuthorityDiscovery    
2021-12-08 11:54:42 ✅ no migration for ImOnline    
2021-12-08 11:54:42 ✅ no migration for Grandpa    
2021-12-08 11:54:42 ✅ no migration for Session    
2021-12-08 11:54:42 ✅ no migration for Historical    
2021-12-08 11:54:42 ⚠️ Offences declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-08 11:54:42 have 0 deferred offences, applying.    
2021-12-08 11:54:42 ⚠️ Staking declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-08 11:54:42 [126973] 💸 Migrating staking to Releases::V7_0_0    
2021-12-08 11:54:42 [126973] 💸 Completed staking migration to Releases::V7_0_0    
2021-12-08 11:54:42 ✅ no migration for ElectionProviderMultiPhase    
2021-12-08 11:54:42 ✅ no migration for Authorship    
2021-12-08 11:54:42 ✅ no migration for TransactionPayment    
2021-12-08 11:54:42 ✅ no migration for Kton    
2021-12-08 11:54:42 ✅ no migration for Balances    
2021-12-08 11:54:42 ✅ no migration for Timestamp    
2021-12-08 11:54:42 ✅ no migration for Babe    
2021-12-08 11:54:42 ✅ no migration for RandomnessCollectiveFlip    
2021-12-08 11:54:42 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 512140800000000, total weight = 512000000000000 (1.000275)
```

**Pull request merged**
