### PR TITLE
Code clean

### PR DESCRIPTION
**Pull request by AsceticBear**
Too many `*` make it hard to tell where a particular variable, trait, or const comes from. And it is hard to tell which is useless in the upstream repo. Related to https://github.com/darwinia-network/darwinia-messages-substrate/pull/189

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
I think the upstream should not take care of how the downstream use it.

**Review by HackFisher — APPROVED** [review]
LGTM

**Comment by AurevoirXavier** [comment]
Need a companion for Darwinia.

**Comment by AsceticBear** [comment]
> Need a companion for Darwinia.

Do it together with other companions in the next Darwinia release?

**Pull request merged**
