### PR TITLE
add mapping token factory setting

### PR DESCRIPTION
**Pull request by xiaoch05**

### CODE REVIEW

**Review by AurevoirXavier — CHANGES_REQUESTED** [review]
Since you've introduced some new storage, please add the migration code that corresponds to them.

**Comment by AsceticBear** [comment]
> Since you've introduced some new storage, please add the migration code that corresponds to them.

The s2s issuing pallet has not been deployed in the pangolin network? So no need to migrate.

**Comment by xiaoch05** [comment]
yes this is the first time to deploy it.

**Comment by AurevoirXavier** [comment]
> > Since you've introduced some new storage, please add the migration code that corresponds to them.
> 
> The s2s issuing pallet has not been deployed in the pangolin network? So no need to migrate.

So the `GenesisBuilder` had never set up the genesis storage; `build_genesis()` had never been executed.

**Comment by AurevoirXavier** [comment]
`OnRuntimeUpgrade` would not trigger the `build_genesis()`.

**Comment by AsceticBear** [comment]
O, you are right, we need a migration here.

**Comment by AsceticBear** [comment]
I guess this is ready for review?

**Review by AsceticBear — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
Use constant instead of storage which means the address can only be modified on runtime upgrade. Is this expected?

**Comment by xiaoch05** [comment]
> Use constant instead of storage which means the address can only be modified on runtime upgrade. Is this expected?

Yes, usually we're forbidden to modify this address. Instead, upgrade the logic contract to upgrade the version. Unless we have a fatal error we may modify this address by runtime upgrade.

**Comment by HackFisher** [comment]
> Use constant instead of storage which means the address can only be modified on runtime upgrade. Is this expected?

I would suggest to use storage for the reason mentioned.

**Comment by HackFisher** [comment]
Only sudo can change this strorage, which we can also say "forbidden".

**Comment by xiaoch05** [comment]
> Only sudo can change this strorage, which we can also say "forbidden".

I agree with this suggestion. It's convenient to debug and deploy. We don't need to deploy the contract first for each network first, then upgrade runtime to match the address.

**Review by AsceticBear — APPROVED** [review]

**Review by HackFisher — APPROVED** [review]
No migration, but LGTM if using sudo set can also meet the requirement.

**Pull request merged**
