### PR TITLE
Update dvm from 318

### PR DESCRIPTION
**Pull request by AsceticBear**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Ready to go?

Safe to make a runtime upgrade on Pangolin?

**Comment by AsceticBear** [comment]
> Ready to go?
> 
> Safe to make a runtime upgrade on Pangolin?

Waiting for CI passed. The change should **upgrade pangolin node client!**, since we change a critical RPC implementation.

**Review by HackFisher — APPROVED** [review]

**Comment by HackFisher** [comment]
For client side storage changes(not just rpc), related to https://github.com/paritytech/frontier/pull/326 ?

Is it ok if we directly upgrade to a new version client? (No client side migration required?)

**Comment by AsceticBear** [comment]
> For client side storage changes(not just rpc), related to [paritytech/frontier#326](https://github.com/paritytech/frontier/pull/326) ?

Yes. Lucky this change has been included in the current pangolin network.

> Is it ok if we directly upgrade to a new version client? (No client-side migration required?)

We just change the RPC returned value. I think no migration needed.

**Review by AurevoirXavier — APPROVED** [review]

**Pull request merged**
