### PR TITLE
Hash Message

### PR DESCRIPTION
**Pull request by AurevoirXavier**
Need a custom migration for Pangolin

### CODE REVIEW

**Review by HackFisher — COMMENTED** [review]
CI failed,

No migration found

**Review by HackFisher — APPROVED** [review]
@AurevoirXavier Will the required migration be included in this PR?

**Comment by HackFisher** [comment]
@AurevoirXavier Will the required migration be included in this PR?

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier Will the required migration be included in this PR?

I'm working on this.

**Comment by AurevoirXavier** [comment]
I think the migration can be ignored because there's no authorities change on pangolin. Just add a tag to remain others.

**Pull request merged**
