### PR TITLE
Release v2.8.1

### PR DESCRIPTION
**Pull request by AurevoirXavier**
Test with the latest DVM updates.
Then we can make a tag for darwinia-v0.12.0.

### CODE REVIEW

**Comment by HackFisher** [comment]
Should we wait for #1050 ?

**Comment by AurevoirXavier** [comment]
> Should we wait for #1050 ?

Nope.
The goal is to test #1031, #1033.

**Comment by AsceticBear** [comment]
> Nope (unnecessary). The goal is to test #1031, #1033. Since #1050 won't affect the downstream (darwinia).

Not necessary. But I suggest including #1050  and #1035  in this release, as these two prs are very close to being merged. One release can save more time to do something else which would be better.

**Comment by AsceticBear** [comment]
Okay. I got it.

**Review by AsceticBear — APPROVED** [review]

**Pull request merged**
