### PR TITLE
Release `v2.9.4`

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
@AsceticBear Please help check the EVM mapping worker `sync_from`.

**Comment by AsceticBear** [comment]
Better to include #1425 in this release

**Comment by AsceticBear** [comment]
> Please help check the EVM mapping worker `sync_from`.

LGTM, It's okay for me if we only reset the pangolin network. How to deal with the existing storage related to the pangoro network?

**Review by HackFisher — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
The genesis is generated before #1425. 

But both spec versions are 29040.

If we release based on this commit, there will be two different runtime logic.

**Pull request merged**
