### PR TITLE
Add Migration

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
```
2022-01-12 15:33:50 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-01-12 15:33:50 [0] 💸 generated 1 npos voters, 1 from validators and 0 nominators    
2022-01-12 15:33:50 [0] 💸 generated 1 npos voters, 1 from validators and 0 nominators    
2022-01-12 15:33:50 [0] 💸 new validator set of size 1 has been processed for era 1    
2022-01-12 15:33:50 [darwinia-claims] Genesis Claims List is Set to EMPTY    
2022-01-12 15:33:53 scraping key-pairs from remote @ 0xd81edc0e5615171970e02fd29d3d74b534c78c5bde7a4df4459c9b7f172a63f5    
2022-01-12 15:33:53 downloading data for all pallets.    
2022-01-12 15:36:25 injecting a total of 17461 keys    
2022-01-12 15:36:27 found matching spec name: "pangolin"    
2022-01-12 15:36:27 found matching spec version: 27020    
2022-01-12 15:36:27 Running migration to v4 for membership with storage version <wasm:stripped>    
2022-01-12 15:36:27 migration, prefix: 'Instance1Membership' ==> 'TechnicalMembership'    
2022-01-12 15:36:27 Running migration to v4 for tips with storage version <wasm:stripped>    
2022-01-12 15:36:27 migration prefix of storage 'Tips': 'Treasury' ==> 'Tips'    
2022-01-12 15:36:27 migration prefix of storage 'Reasons': 'Treasury' ==> 'Tips'    
2022-01-12 15:36:27 Running migration to v4 for collective with storage version <wasm:stripped>    
2022-01-12 15:36:27 migration, prefix: 'Instance1Collective' ==> 'Council'    
2022-01-12 15:36:27 Running migration to v4 for collective with storage version <wasm:stripped>    
2022-01-12 15:36:27 migration, prefix: 'Instance2Collective' ==> 'TechnicalCommittee'    
2022-01-12 15:36:27 ⚠️ System declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2022-01-12 15:36:27 ✅ no migration for BSC    
2022-01-12 15:36:27 ✅ no migration for Substrate2SubstrateIssuing    
2022-01-12 15:36:27 ✅ no migration for TransactionPause    
2022-01-12 15:36:27 ✅ no migration for FeeMarket    
2022-01-12 15:36:27 ✅ no migration for BridgePangoroMessages    
2022-01-12 15:36:27 ✅ no migration for BridgePangoroGrandpa    
2022-01-12 15:36:27 ✅ no migration for BridgePangoroDispatch    
2022-01-12 15:36:27 ✅ no migration for Ethereum    
2022-01-12 15:36:27 ✅ no migration for EVM    
2022-01-12 15:36:27 ✅ no migration for TronBacking    
2022-01-12 15:36:27 ✅ no migration for EthereumRelayAuthorities    
2022-01-12 15:36:27 ✅ no migration for EthereumRelayerGame    
2022-01-12 15:36:27 ✅ no migration for EthereumIssuing    
2022-01-12 15:36:27 ✅ no migration for EthereumBacking    
2022-01-12 15:36:27 ✅ no migration for EthereumRelay    
2022-01-12 15:36:27 ✅ no migration for Multisig    
2022-01-12 15:36:27 ✅ no migration for Proxy    
2022-01-12 15:36:27 ✅ no migration for Scheduler    
2022-01-12 15:36:27 ✅ no migration for Recovery    
2022-01-12 15:36:27 ✅ no migration for Society    
2022-01-12 15:36:27 ✅ no migration for Identity    
2022-01-12 15:36:27 ✅ no migration for Utility    
2022-01-12 15:36:27 ⚠️ Vesting declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2022-01-12 15:36:27 ✅ no migration for Claims    
2022-01-12 15:36:27 ✅ no migration for Sudo    
2022-01-12 15:36:27 ✅ no migration for Bounties    
2022-01-12 15:36:27 ✅ no migration for Tips    
2022-01-12 15:36:27 ✅ no migration for KtonTreasury    
2022-01-12 15:36:27 ✅ no migration for Treasury    
2022-01-12 15:36:27 ✅ no migration for TechnicalMembership    
2022-01-12 15:36:27 ✅ no migration for PhragmenElection    
2022-01-12 15:36:27 ✅ no migration for TechnicalCommittee    
2022-01-12 15:36:27 ✅ no migration for Council    
2022-01-12 15:36:27 ✅ no migration for Democracy    
2022-01-12 15:36:27 ✅ no migration for HeaderMMR    
2022-01-12 15:36:27 ✅ no migration for AuthorityDiscovery    
2022-01-12 15:36:27 ✅ no migration for ImOnline    
2022-01-12 15:36:27 ✅ no migration for Grandpa    
2022-01-12 15:36:27 ✅ no migration for Session    
2022-01-12 15:36:27 ✅ no migration for Historical    
2022-01-12 15:36:27 ⚠️ Offences declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2022-01-12 15:36:27 have 0 deferred offences, applying.    
2022-01-12 15:36:27 ⚠️ Staking declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2022-01-12 15:36:27 ✅ no migration for ElectionProviderMultiPhase    
2022-01-12 15:36:27 ✅ no migration for Authorship    
2022-01-12 15:36:27 ✅ no migration for TransactionPayment    
2022-01-12 15:36:27 ✅ no migration for Kton    
2022-01-12 15:36:27 ✅ no migration for Balances    
2022-01-12 15:36:27 ✅ no migration for Timestamp    
2022-01-12 15:36:27 ✅ no migration for Babe    
2022-01-12 15:36:27 post-migration, prefix: 'Instance1Membership' ==> 'TechnicalMembership'    
2022-01-12 15:36:27 post-migration prefix of storage 'Tips': 'Treasury' ==> 'Tips'    
2022-01-12 15:36:27 post-migration prefix of storage 'Reasons': 'Treasury' ==> 'Tips'    
2022-01-12 15:36:27 post-migration, prefix: 'Instance1Collective' ==> 'Council'    
2022-01-12 15:36:27 post-migration, prefix: 'Instance2Collective' ==> 'TechnicalCommittee'    
2022-01-12 15:36:27 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 2000275000000, total weight = 2000000000000 (1.0001375)  
```

**Comment by AsceticBear** [comment]
Red CI

**Comment by AurevoirXavier** [comment]
Just check the code.

#1036 will fix this.

**Comment by AsceticBear** [comment]
I see, Then, it's would be better to change your pr base to `xavier-release`. then we make a final release.

**Pull request merged**
